version: "3"

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./public:/source
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
