version: "2"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./site:/source
            - ./site.conf:/etc/nginx/conf.d/default.conf
