version: "3"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./public:/source
            - ./site.conf:/etc/nginx/conf.d/default.conf
